//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="MojeDane", IsNullable=false)]
public partial class ListaOsób {
    
    private ListaOsóbOsoba[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Osoba")]
    public ListaOsóbOsoba[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaOsóbOsoba {
    
    private string imięField;
    
    private string nazwiskoField;
    
    private string dataUrField;
    
    private string adresStalyField;
    
    private string adresTymField;
    
    private ListaOsóbOsobaListaZajęć[] listaZajęćField;
    
    /// <remarks/>
    public string Imię {
        get {
            return this.imięField;
        }
        set {
            this.imięField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public string DataUr {
        get {
            return this.dataUrField;
        }
        set {
            this.dataUrField = value;
        }
    }
    
    /// <remarks/>
    public string AdresStaly {
        get {
            return this.adresStalyField;
        }
        set {
            this.adresStalyField = value;
        }
    }
    
    /// <remarks/>
    public string AdresTym {
        get {
            return this.adresTymField;
        }
        set {
            this.adresTymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListaZajęć")]
    public ListaOsóbOsobaListaZajęć[] ListaZajęć {
        get {
            return this.listaZajęćField;
        }
        set {
            this.listaZajęćField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaOsóbOsobaListaZajęć {
    
    private ListaOsóbOsobaListaZajęćZajęcie[] zajęcieField;
    
    private string nazwaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zajęcie")]
    public ListaOsóbOsobaListaZajęćZajęcie[] Zajęcie {
        get {
            return this.zajęcieField;
        }
        set {
            this.zajęcieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaOsóbOsobaListaZajęćZajęcie {
    
    private string nazwaField;
    
    private string ocenaField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string Ocena {
        get {
            return this.ocenaField;
        }
        set {
            this.ocenaField = value;
        }
    }
}
